#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page.
# The redirection is configured to be "301 Moved Permanently"

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
